### ISSUE TITLE
GitHub Enterprise Support

### ISSUE THREAD

**Issue by supergibbs** [thoughtbot/pipe-it-down#10]
We host our own instance of GitHub internally. It would be great to be able to add domains in a settings dialog that activate the extension in addition to `https://github.com/*`

**Comment by thorncp** [comment]
Hi @supergibbs,

The domains are whitelisted in the manifest, which is included in the bundle (a zip file) that's submitted to the Web Store. As far as I know, it's not possible to dynamically update which domains the extension supports. If I'm wrong, I'd love to know how!

I think your best bet would be to clone this repo, change the [manifest](https://github.com/thoughtbot/pipe-it-down/blob/master/src/manifest.json#L14) to allow your domain, then follow the development [installation instructions](https://github.com/thoughtbot/pipe-it-down/tree/87129bd21d4b7c152207b1990ed461ea30d4c5c0#installing-for-development).
