### ISSUE TITLE
Firefox ?

### ISSUE THREAD

**Issue by JulienItard** [thoughtbot/pipe-it-down#7]
Really nice feature ! Do you plan to add it to Firefox as well ?

**Comment by thorncp** [comment]
Hey @JulienItard, thanks!

I don't have experience with Firefox addons, but it seems they're making strides to support the same structure as Chrome. However, they don't currently have full feature parity: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Chrome_incompatibilities. Notably, the `chrome.storage` API isn't supported yet.

I like the idea of supporting Firefox, but I don't like the idea of fracturing the code base for multiple platforms. I don't use Firefox, so I think that version would inherently be at a disadvantage - I'd rather not support Firefox at all, than to support it poorly.

I'm open to reconsider this when Firefox's Chrome compatibility matures a bit more.

**Comment by JulienItard** [comment]
@thorncp Thanks for you awnser.
