### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by vemv** [thoughtbot/pipe-it-down#9]
Hi!

I installed this yesterday and I haven't seen it working yet. i.e. there's no buttons added, no difference.

Is there any info I can provide for debugging?

Cheers - Victor

**Comment by thorncp** [comment]
Hi @vemv,

I heard from someone else that nothing seemed to be happening and the reported fix was to, oddly enough, uninstall then reinstall the plugin. Did you try that?

If that doesn't work, we'll dig deeper.

**Comment by vemv** [comment]
Did the trick. Thank you!
